// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-45opEOdSj6yAZ5bnldgMPeRmKK9fqFA',
    appId: '1:78892459508:web:6abad3de2c19ba5a7945a1',
    messagingSenderId: '78892459508',
    projectId: 'sheild-91d84',
    authDomain: 'sheild-91d84.firebaseapp.com',
    storageBucket: 'sheild-91d84.firebasestorage.app',
    measurementId: 'G-QM1RVX2RVE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8g2S6SvftCeqpRIJEOXYdT-nCZD9hyhk',
    appId: '1:78892459508:android:bb0c0cf711a987077945a1',
    messagingSenderId: '78892459508',
    projectId: 'sheild-91d84',
    storageBucket: 'sheild-91d84.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5B8uEbtC5FzcmibmW0O96ykL4Hle_LVU',
    appId: '1:78892459508:ios:2c060a5d72581d9d7945a1',
    messagingSenderId: '78892459508',
    projectId: 'sheild-91d84',
    storageBucket: 'sheild-91d84.firebasestorage.app',
    iosBundleId: 'com.example.sheildApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5B8uEbtC5FzcmibmW0O96ykL4Hle_LVU',
    appId: '1:78892459508:ios:2c060a5d72581d9d7945a1',
    messagingSenderId: '78892459508',
    projectId: 'sheild-91d84',
    storageBucket: 'sheild-91d84.firebasestorage.app',
    iosBundleId: 'com.example.sheildApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-45opEOdSj6yAZ5bnldgMPeRmKK9fqFA',
    appId: '1:78892459508:web:005c0bd73e77bc027945a1',
    messagingSenderId: '78892459508',
    projectId: 'sheild-91d84',
    authDomain: 'sheild-91d84.firebaseapp.com',
    storageBucket: 'sheild-91d84.firebasestorage.app',
    measurementId: 'G-7EFKJZ0L1Q',
  );
}
